NHSDigital/nhs-notify-reporting

.github/CODEOWNERS
Replacing Ed with Aiden as Codeowner.
Ed has rolled off the project and Aiden has joined in his place.
---
=> CCM-5624: Replace Ed with Aiden as Codeowner

.github/CODEOWNERS
=> CCM-5624: Add Platform team to codeowners

.github/workflows/cicd-1-pull-request.yaml, .github/workflows/stage-1-commit.yaml
Changing the environment name in github from dev to main for consistency.
---
=> CCM-5543 Change Environment Name to Main

infrastructure/terraform/deploy.sh
Missing deploy.sh required for CD pipeline.
---
=> CCM-5543: Add Missing Deploy Script

infrastructure/terraform/deploy.sh
=> CCM-5543: Fix Deploy Script

infrastructure/terraform/components/reporting/athena_data_catalog_reporting.tf, infrastructure/terraform/components/reporting/variables.tf, infrastructure/terraform/etc/group_nhs-notify-reporting-dev.tfvars
Adds a Data Catalog for each environment, that points to the appropriate core account. 
To allow athena queries to be run against an environment's core transaction_history table.
---
=> CCM-5669: New Data Catalog

infrastructure/terraform/etc/env_eu-west-2_main.tfvars, infrastructure/terraform/etc/group_nhs-notify-reporting-dev.tfvars
=> CCM-5669: Fix core account variable

infrastructure/terraform/components/reporting/scripts/sql/queries/request_item_status.sql, infrastructure/terraform/etc/env_eu-west-2_prod.tfvars
Changes from MP and JT prior to initial production deployment
---
=> Changes for initial prod deployment

.gitleaksignore, infrastructure/terraform/components/reporting/autoscaling_group_powerbi_gateway.tf, infrastructure/terraform/components/reporting/launch_template_powerbi_gateway.tf, infrastructure/terraform/components/reporting/module_powerbi_gateway_vpc.tf, infrastructure/terraform/etc/env_eu-west-2_prod.tfvars
Fixes ported over from working gateway branch to allow for NOT deploying the gateway. 
---
=> CCM-6265: Initial Production Deployment Fixes

infrastructure/terraform/components/reporting/scripts/sql/queries/request_item_plan_completed_summary.sql
A query fix that makes it easier to pick up correct values where a row has been manually corrected to a state not usually created by the system.
---
=> Fix for data quality / manually corrected data

infrastructure/terraform/components/reporting/files/state.json.tmpl, infrastructure/terraform/components/reporting/ssm_parameter_hash_key.tf
Replace underscore with hyphen in param name
---
=> TF Test fix

infrastructure/terraform/components/reporting/scripts/sql/migration/request_item_plan_completed_summary.sql, infrastructure/terraform/components/reporting/scripts/sql/migration/request_item_status.sql, infrastructure/terraform/components/reporting/scripts/sql/queries/request_item_plan_completed_summary.sql, infrastructure/terraform/components/reporting/scripts/sql/queries/request_item_status.sql
Fixes to handle old second-precision timestamps better (use terminal states as tie breaker)
---
=> CCM-5360 Data migration fixes

.gitleaksignore, README.md, infrastructure/terraform/components/reporting/null_resource_request_item_plan_completed_summary_table.tf, infrastructure/terraform/components/reporting/null_resource_request_item_status_table.tf, infrastructure/terraform/components/reporting/scripts/add_column.sh, infrastructure/terraform/components/reporting/scripts/create_table.sh, infrastructure/terraform/components/reporting/scripts/execute_query.sh, infrastructure/terraform/components/reporting/scripts/sql/queries/request_item_plan_completed_summary.sql, infrastructure/terraform/components/reporting/scripts/sql/queries/request_item_status.sql, infrastructure/terraform/components/reporting/scripts/sql/tables/request_item_plan_completed_summary.sql, infrastructure/terraform/components/reporting/scripts/sql/tables/request_item_status.sql, scripts/config/vale/styles/Vocab/words/accept.txt
Added new columns to staging tables to support additional reporting requirements.
Refactored null_resource support so that both table addition and column addition are supported rather than single check.
Changed query execution to cater for asynchronous execution by polling the query status.
---
=> CCM-5609 Add new columns for reporting on ODS codes and Contact Detail Overrides

.gitleaksignore, README.md, infrastructure/terraform/components/reporting/files/state.json.tmpl, infrastructure/terraform/components/reporting/sfn_state_machine_athena.tf
Allow ingestion queries to run in multiple passes so that one can depend on the outputs of another.
Improves scalability performance, reduces cost, reduces duplication
---
=> CCM-6530 two pass ingestion

infrastructure/terraform/etc/env_eu-west-2_prod.tfvars
Enable the gateway in Production.
---
=> CCM-5362: Enable PowerBI On-Premises Gateway for Production

infrastructure/terraform/components/reporting/ssm_maintenance_window_task_patch_task.tf
Removing unnecessary server role reference that broke the task execution.
---
=> CCM-5362: Fix Patch Assume Role

infrastructure/terraform/components/reporting/null_resource_request_item_plan_completed_summary_table.tf, infrastructure/terraform/components/reporting/null_resource_request_item_status_table.tf
Prevent DDL running in parallel
---
=> CCM-0000 Prevent parallel execution of column addition

infrastructure/terraform/components/reporting/scripts/sql/migration/request_item_plan_completed_summary.sql, infrastructure/terraform/components/reporting/scripts/sql/migration/request_item_plan_status.sql, infrastructure/terraform/components/reporting/scripts/sql/migration/request_item_status.sql
Updated data migration scripts to include v4.26 changes.
These are in the repo just for reference, they're not executed automatically.
---
=> Updated migration queries to support v4.26 of Notify

README.md, infrastructure/terraform/components/reporting/scripts/sql/README.md
=> Readme updates

infrastructure/terraform/components/acct/data_iam_policy_document_sso_read_only_table_access.tf, infrastructure/terraform/components/reporting/athena_named_query_request_item_plan_completed_summary_batch.tf, infrastructure/terraform/components/reporting/iam_instance_profile_powerbi_gateway.tf, infrastructure/terraform/components/reporting/null_resource_request_item_plan_completed_summary_batch_table.tf, infrastructure/terraform/components/reporting/scripts/sql/README.md, infrastructure/terraform/components/reporting/scripts/sql/ingestion/request_item_plan_completed_summary_batch.sql, infrastructure/terraform/components/reporting/scripts/sql/optimize/request_item_plan_completed_summary_batch.sql, infrastructure/terraform/components/reporting/scripts/sql/tables/request_item_plan_completed_summary_batch.sql, infrastructure/terraform/components/reporting/scripts/sql/vacuum/request_item_plan_completed_summary_batch.sql, infrastructure/terraform/components/reporting/sfn_state_machine_housekeeping.tf, infrastructure/terraform/components/reporting/sfn_state_machine_ingestion.tf, infrastructure/terraform/components/reporting/variables.tf, infrastructure/terraform/etc/env_eu-west-2_prod.tfvars, infrastructure/terraform/etc/env_eu-west-2_ref.tfvars
Adds a new aggregation table that includes additional dimensions that include the batch references.
This is needed for backwards compatibility with the XLS for vaccinations, but is unsuitable for newer non-batch use cases.
Only whitelisted clients will be added to the new aggregation.
---
=> CCM-6891 Vaccs Backwards Compatibility

README.md, infrastructure/terraform/components/acct/data_iam_policy_document_sso_read_only_table_access.tf, infrastructure/terraform/components/reporting/iam_instance_profile_powerbi_gateway.tf, infrastructure/terraform/components/reporting/null_resource_request_item_plan_completed_summary_all_view.tf, infrastructure/terraform/components/reporting/scripts/create_replace_view.sh, infrastructure/terraform/components/reporting/scripts/sql/views/request_item_plan_completed_summary_all.sql, scripts/config/vale/styles/Vocab/words/accept.txt
* Add a mechanism for creating database views
* Add a view to unify two underlying tables with dissimilar columns to allow them to be queried as one.
Reports for vaccinations rely on exposing batch information, but this can't be applied to all use cases since it will perform poorly in cases when batches are very small (or single-send messages).
This change allows us to display both with-batch and without-batch clients so they can be queried uniformly.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the …
=> CCM-6891 vaccs compatibility view

infrastructure/terraform/components/reporting/null_resource_request_item_plan_completed_summary_all_view.tf, infrastructure/terraform/components/reporting/null_resource_request_item_status_summary_all_view.tf
Fix dependencies as there is a deploy-time dependency that I'd originally thought was a run-time dependency.
---
=> Fix dependencies

infrastructure/terraform/components/acct/data_iam_policy_document_sso_read_only_table_access.tf, infrastructure/terraform/components/reporting/iam_instance_profile_powerbi_gateway.tf, infrastructure/terraform/components/reporting/null_resource_dates_view.tf, infrastructure/terraform/components/reporting/null_resource_request_item_plan_completed_summary_batch_table.tf, infrastructure/terraform/components/reporting/null_resource_request_item_plan_completed_summary_table.tf, infrastructure/terraform/components/reporting/null_resource_request_item_plan_status_table.tf, infrastructure/terraform/components/reporting/null_resource_request_item_status_summary_batch_table.tf, infrastructure/terraform/components/reporting/null_resource_request_item_status_summary_table.tf, infrastructure/terraform/components/reporting/null_resource_request_item_status_table.tf, infrastructure/terraform/components/reporting/scripts/sql/views/dates.sql, infrastructure/terraform/components/reporting/scripts/sql/views/request_item_plan_completed_summary_all.sql, infrastructure/terraform/components/reporting/scripts/sql/views/request_item_status_summary_all.sql
* Reinstates the dates sequence view
* Removes some old dependencies that were rendered obsolete on an earlier script improvement
---
=> CCM-0000 Reinstate dates view and remove spurious dependencies

infrastructure/terraform/components/acct/data_iam_policy_document_sso_read_only_table_access.tf
Added missing permission identified in PowerBI Review
---
=> CCM-0000 Added missing permission

infrastructure/terraform/components/acct/data_iam_policy_document_sso_read_only_table_access.tf
=> CCM-0000 Add missing permission

infrastructure/terraform/components/reporting/sfn_state_machine_completed_comms_report.tf
Fix regression in earlier IAM change
---
=> CCM-6474 report generation bugfix

infrastructure/terraform/etc/env_eu-west-2_uat.tfvars
Adds a UAT environment to allow for cross-account access.
(https://nhsd-jira.digital.nhs.uk/browse/CCM-7225)
New tfvars file for UAT.
**Cannot be merged until https://github.com/NHSDigital/comms-mgr/pull/267 is merged and deployed.**
---
=> CCM-7225: Enable Reporting for UAT - Reporting Account

infrastructure/terraform/components/reporting/scheduler_schedule_sf_completed_comms_report_scheduler.tf, infrastructure/terraform/components/reporting/scheduler_schedule_sf_ingestion_scheduler.tf, infrastructure/terraform/components/reporting/scripts/sql/reports/completed_comms_report.sql
Updated the completed comms report to handle when we have a requestItem but with no plans.
Details of testing carried out for other scenarios are documented here https://nhsd-jira.digital.nhs.uk/browse/CCM-5656
---
=> CCM-5656: update report for parallel send

infrastructure/terraform/components/reporting/null_resource_request_item_plan_status_table.tf, infrastructure/terraform/components/reporting/scripts/sql/ingestion/request_item_plan_status.sql, infrastructure/terraform/components/reporting/scripts/sql/tables/request_item_plan_status.sql
Adds a new column to the reporting data to identify specific objects in PDS.
This is an enable for future reporting changes needed by PDS, in order to identify specific data fixes.
---
=> Add new column to table and ingestion script

infrastructure/terraform/components/reporting/cloudwatch_metric_alarm_overdue_request_item_plans.tf, infrastructure/terraform/components/reporting/cloudwatch_metric_alarm_overdue_request_items.tf, infrastructure/terraform/components/reporting/cloudwatch_metric_alarm_overdue_requests.tf, infrastructure/terraform/components/reporting/sfn_state_machine_watchdog.tf, infrastructure/terraform/components/reporting/templates/watchdog.json.tmpl
Bug fix to scope metrics and alarms by environment.
---
=> CCM-7708 Watchdog Queries Bug Fix

infrastructure/terraform/components/acct/variables.tf, infrastructure/terraform/etc/env_eu-west-2_int.tfvars, infrastructure/terraform/etc/env_eu-west-2_main.tfvars, infrastructure/terraform/etc/env_eu-west-2_prod.tfvars, infrastructure/terraform/etc/env_eu-west-2_ref.tfvars, infrastructure/terraform/etc/env_eu-west-2_uat.tfvars, infrastructure/terraform/etc/group_nhs-notify-reporting-dev.tfvars, infrastructure/terraform/etc/group_nhs-notify-reporting-prod.tfvars
Updating tfvars for reporting to support Observability access 
---
=> CCM-8202: Updating tfvars to support Observability Grafana access

infrastructure/terraform/components/acct/iam_role_grafana_access.tf
IAM Role for Grafana access from Observability account.
---
=> CCM-8202: Grafana Cross Account Access

infrastructure/terraform/etc/env_eu-west-2_int.tfvars, infrastructure/terraform/etc/env_eu-west-2_main.tfvars, infrastructure/terraform/etc/env_eu-west-2_prod.tfvars, infrastructure/terraform/etc/env_eu-west-2_ref.tfvars, infrastructure/terraform/etc/env_eu-west-2_uat.tfvars
Updating individual tfvars for envs for obs account id
---
=> CCM-8742: Adding obs account to individual tfvars

infrastructure/terraform/components/acct/data_iam_policy_document_sso_read_only_table_access.tf, infrastructure/terraform/components/reporting/iam_instance_profile_powerbi_gateway.tf, infrastructure/terraform/components/reporting/null_resource_latency_percentiles_view.tf, infrastructure/terraform/components/reporting/null_resource_letters_invoice_units_view.tf, infrastructure/terraform/components/reporting/scripts/sql/views/latency_percentiles.sql, infrastructure/terraform/components/reporting/scripts/sql/views/letters_invoice_units.sql
Two new views added to support additional PowerBI dashboards
Requests from stakeholders to have information on latency and letter invoices
---
=> CCM-6801 Additional views for dashboard

infrastructure/terraform/components/reporting/scripts/sql/views/latency_percentiles.sql
Minor tweak to optimise query and increase resolution on dashboard
---
=> CCM-6801 athena view iteration

infrastructure/terraform/components/reporting/README.md, infrastructure/terraform/components/reporting/locals_remote_state.tf, infrastructure/terraform/components/reporting/variables.tf, infrastructure/terraform/etc/env_eu-west-2_int.tfvars, infrastructure/terraform/etc/env_eu-west-2_main.tfvars, infrastructure/terraform/etc/env_eu-west-2_prod.tfvars, infrastructure/terraform/etc/env_eu-west-2_ref.tfvars, infrastructure/terraform/etc/env_eu-west-2_uat.tfvars
Acct component for nonprod (which all exists in the dev account) is called main.
Acct component in prod is called prod.
Reporting component doesn't use group.
---
=> CCM-10541: Reporting Account Environment Variable

infrastructure/terraform/components/reporting/templates/completed_batch_report.json.tmpl, infrastructure/terraform/components/reporting/templates/completed_comms_report.json.tmpl
Add an explicit error check to step functions to prevent silent failures.
Also took the opportunity to fix up some inconsistent capitalisation of fields.
The issue raised in https://nhsd-jira.digital.nhs.uk/browse/CCM-10807 was a silent failure, and as such did not trigger our Cloudwatch monitoring.
This change adds an explicit check that the report has been generated and in the right location. If the check fails the step function will also fail and this will be visible in Cloudwatch.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data …
=> CCM-10913 prevent silent failures

infrastructure/terraform/components/reporting/templates/completed_batch_report.json.tmpl
Fix bug due to copy-and-paste error.
Fix bug due to copy-and-paste error.
---
=> CCM-10913 Bug fix

infrastructure/terraform/components/reporting/iam_role_policy_attachment_s3_backup.tf
=> CCM-10934: Fix managed policy arn

infrastructure/terraform/components/reporting/locals_remote_state.tf, infrastructure/terraform/components/reporting/locals_tfscaffold.tf
Modify the project name to be in line with the new bootstrap and acct components.
---
=> CCM-11095: Reporting Cutover - Change Project Name for Remote States

.github/workflows/pr_closed.yaml, .github/workflows/release_created.yaml
=> CCM-11942: Fix runs-on
